<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dse.Io.Abstractions\Dse.Io.Abstractions.csproj" />
    <ProjectReference Include="..\Dse.Realtime\Dse.Realtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dse.Modbus.Tests" />
  </ItemGroup>

</Project>
